server:
  port: 9009

spring:
  application:
    name: redis-service
  #redis配置
  redis:
    host: localhost  #redis配置ip
    port: 6379
    password: 123456


    #采用lettuce方式连接
    lettuce:
      shutdown-timeout: 100s # 关闭超时时间
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: 30s # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://47.97.210.181:3306/supplier?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: xiedong
    password: root


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/

###设置feign客户端超时时间

###开启Hystrix断路器
feign:
  hystrix:
    enabled: true
###配置请求超时时间
