server:
  port: 9528
spring:
  application:
    name: gateway-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://47.97.210.181:3306/supplier?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  cloud:
    gateway:
      routes:
        - id: payment_routh
          uri: lb://merchant-service #9999 merchant-service的路径
          predicates:
            - Path=/**    #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: gateway9528
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone:  http://eureka7003.com:7003/eureka/, http://eureka7002.com:7002/eureka/
