server:
  port: 9999

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/

feign:
  hystrix:
    enabled: true
spring:
  application:
    name: merchant-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://47.97.210.181:3306/supplier?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true